#!/usr/bin/bash

DB_SOURCE="https://github.com/f1db/f1db/releases/latest/download/f1db-sqlite.zip"
DB_NAME="f1db.db"

rm -rf data
mkdir -p data

wget $DB_SOURCE -P data
unzip data/f1db-sqlite.zip -d data/
rm data/f1db-sqlite.zip